"""Initial schema: users, calorie_profiles, foods, food_log

Revision ID: b87b75768f04
Revises: 
Create Date: 2026-06-01 22:55:11.954289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87b75768f04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_password'), ['password'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('calorie_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('carbs', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fat', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('protein', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('calories', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calorie_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calorie_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('carbs', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fat', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('protein', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('calories', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foods_user_id'), ['user_id'], unique=False)

    op.create_table('food_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mealtime', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='mealtime'), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('quantity_grams', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('carbs', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fat', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('protein', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('calories', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_log_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_log_user_id'))

    op.drop_table('food_log')
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foods_user_id'))

    op.drop_table('foods')
    with op.batch_alter_table('calorie_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calorie_profiles_user_id'))

    op.drop_table('calorie_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_password'))

    op.drop_table('users')
    # ### end Alembic commands ###
